#pragma once

#ifndef _AR_LOG_CHANNELS_
#define _AR_LOG_CHANNELS_

#include "Logging/LogMacros.h"

#define LOG_API ARRANGER_API

LOG_API DECLARE_LOG_CATEGORY_EXTERN(LogARPhysics, Log, All);
LOG_API DECLARE_LOG_CATEGORY_EXTERN(LogARRepository, Log, All);
LOG_API DECLARE_LOG_CATEGORY_EXTERN(LogAREditorAsset, Log, All);
LOG_API DECLARE_LOG_CATEGORY_EXTERN(LogARBattle, Log, All);
LOG_API DECLARE_LOG_CATEGORY_EXTERN(LogARInput, Log, All);
LOG_API DECLARE_LOG_CATEGORY_EXTERN(LogARRangeDetector, Log, All);

#undef LOG_API

#endif // _AR_LOG_CHANNELS_